### ISSUE TITLE
FuMS.pbo -> config.cpp -> Declaration 'units[] = {];' is defined improperly

### ISSUE THREAD

**Issue by SirFrostingham** [horbin/FuMS-HC-Exile#1]
In FuMS.pbo -> config.cpp:

Line 4 (left curly brace and a right bracket):
        units[] = {];
should be:
        units[] = {};

**Comment by horbin** [comment]
Moose, thanks!  Will be fixed in the next update.

**Comment by canuckbrian** [comment]
Closing. Issue was fixed a long time ago.
