### ISSUE TITLE
NO entry 'bin\config.bin/CfgWeapons.'.

### ISSUE THREAD

**Issue by rjclarkewp007** [horbin/FuMS-HC-Exile#15]
Hi

After adding this mod any player that joins the server will receive this error. Clicking on close will close the error and the player can still join. Found that some loot creates are empty though. Any ideas where to start looking?

RPT log:
11:06:38 Warning Message: No entry 'bin\config.bin/CfgWeapons.'.
11:06:38 Warning Message: No entry '.scope'.
11:06:38 Warning Message: '/' is not a value
11:06:38 Warning Message: Error: creating weapon  with scope=private
11:06:38 Warning Message: No entry '.displayName'.
11:06:38 Warning Message: '/' is not a value
11:06:38 Warning Message: No entry '.nameSound'.
11:06:38 Warning Message: '/' is not a value
11:06:38 Warning Message: No entry '.type'.
11:06:38 Warning Message: '/' is not a value
11:06:38 Warning Message: No entry '.picture'.
11:06:38 Warning Message: '/' is not a value
11:06:38 Warning Message: No entry '.Library'.
11:06:38 Warning Message: No entry '.libTextDesc'.
11:06:38 Warning Message: '/' is not a value
11:06:38 Warning Message: No entry '.model'.
11:06:38 Warning Message: '/' is not a value
11:06:38 Warning Message: No entry '.simulation'.
11:06:38 Warning Message: '/' is not a value
11:06:38 Warning Message: No entry '.fireLightDuration'.
11:06:38 Warning Message: '/' is not a value
11:06:38 Warning Message: No entry '.fireLightIntensity'.
11:06:38 Warning Message: '/' is not a value
11:06:38 Warning Message: No entry '.fireLightDiffuse'.
11:06:38 Warning Message: Size: '/' not an array
11:06:38 Warning Message: Size: '/' not an array
11:06:38 Warning Message: No entry '.fireLightAmbient'.
11:06:38 Warning Message: Size: '/' not an array
11:06:38 Warning Message: Size: '/' not an array
11:06:38 Warning Message: No entry '.weaponLockDelay'.
11:06:38 Warning Message: '/' is not a value
11:06:38 Warning Message: No entry '.weaponLockSystem'.
11:06:38 Warning Message: '/' is not a value
11:06:38 Warning Message: No entry '.cmImmunity'.
11:06:38 Warning Message: '/' is not a value
11:06:38 Warning Message: No entry '.weight'.
11:06:38 Warning Message: '/' is not a value
11:06:38 Warning Message: No entry '.lockingTargetSound'.
11:06:38 Warning Message: Size: '/' not an array
11:06:38 Warning Message: No entry '.lockedTargetSound'.
11:06:38 Warning Message: Size: '/' not an array
11:06:38 Warning Message: No entry '.detectRange'.
11:06:38 Warning Message: '/' is not a value
11:06:38 Warning Message: No entry '.muzzles'.
11:06:38 Warning Message: Size: '/' not an array
11:06:38 Error: Object(4 : 69) not found
11:06:38 Server: Object 4:78 not found (message Type_120)
11:06:38 Server: Object 4:77 not found (message Type_92)
11:06:38 Error: Object(4 : 77) not found
11:06:38 Server: Object 4:81 not found (message Type_126)
11:06:38 Server: Object 4:82 not found (message Type_114)
11:06:38 Server: Object 4:80 not found (message Type_459)
11:06:38 Server: Object 4:79 not found (message Type_459)

**Comment by ExiledHeisenberg** [comment]
Thanks.  This is because CUP support is enabled by default on accident.  I have updated it in the dev release, but you can go to CAMS\CAMSconfig.sqf and comment out the CUPW, CUPV, and CUPW lines, and fix the comma after Apex
