### ISSUE TITLE
FuMS Not Passing Scripts to Headless Client

### ISSUE THREAD

**Issue by smithb895** [horbin/FuMS-HC-Exile#19]
Does this repo still work with ArmA 3 ExileMod?  I tried to get it working but could not.  HC starts up fine and connects, FuMS never passes any scripts to HC though, no mention of FuMS.  I heard mixed reports that this broke with ArmA 3 updates and no longer works, so I just wanted to check.  Thanks!

**Comment by ExiledHeisenberg** [comment]
Still runs perfectly as downloaded.  I'm running it now and still developing it.

**Comment by smithb895** [comment]
Good to know! Thank you for the response.  Hmm, i wonder what I'm doing wrong then.  When I check the log on the HC, it seems the player object is Null and I'm thinking that may be why it gets stuck?  Any ideas what may be causing this?
